# Generated by Django 2.2.5 on 2022-08-30 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220830_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='superhose',
            new_name='superhost',
        ),
    ]
